docbook-docx {

    style-scripts = ["arabicParagraph"]

    arabic {
      font-name = "KFGQPC Uthman Taha Naskh"

      normal {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 22
      }

      small {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 16
      }

      bold {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = ${docbook-docx.arabic.normal.font-size}
      }

      heading {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 32
      }

      caption {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 24
        color = 099BDD
      }

      translation {
        font-name = "Arabic Typesetting"
        font-size = 20
      }
    }
}