docbook-docx {

    style-handlers {
        arabicBold = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
        arabicHeading1 = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
        arabicNormal = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
        arabicSmall = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
        arabicSmallGray = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
        arabicTableCaption = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
        translation = com.alphasystem.docbook.handler.impl.JavaScriptBasedStyleHandler
    }

    scripts += {
        name = "arabicParagraph"
        type = "org.docx4j.wml.Style"
    }
    scripts += {
        name = "arabicNormal"
        type = "org.docx4j.wml.RPr"
    }
    scripts += {
        name = "arabicSmall"
        type = "org.docx4j.wml.RPr"
    }
    scripts += {
        name = "arabicSmallGray"
        type = "org.docx4j.wml.RPr"
    }
    scripts += {
        name = "arabicBold"
        type = "org.docx4j.wml.RPr"
    }
    scripts += {
        name = "arabicHeading1"
        type = "org.docx4j.wml.RPr"
    }
    scripts += {
        name = "arabicTableCaption"
        type = "org.docx4j.wml.RPr"
    }
    scripts += {
        name = "translation"
        type = "org.docx4j.wml.RPr"
    }

    arabic {
      font-name = "KFGQPC Uthman Taha Naskh"

      normal {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 22
      }

      small {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 16
      }

      bold {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = ${docbook-docx.arabic.normal.font-size}
      }

      heading {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 32
      }

      caption {
        font-name = ${docbook-docx.arabic.font-name}
        font-size = 24
        color = 099BDD
      }

      translation {
        font-name = "Arabic Typesetting"
        font-size = 20
      }
    }
}
