/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id("io.github.sfali23.gradle-semantic-versioning-release") version "0.4.1"
    }
}

plugins {
    id("io.github.sfali23.gradle-semantic-versioning-release")
}

semverrelease {
    addUnReleasedCommitsToTagComment.set(true)
}

rootProject.name = "docbook-2-docx-parent"

include(":docbook-2-docx-common")
include(":docbook-model")
include(":asciidoctor-adapter")
include(":docbook-2-docx")
include(":asciidoc-docx-cli")
